### PR TITLE
Notes about learning algorithms

### PR DESCRIPTION
**Pull request by Yuya-Furusawa**
Review the notes on learning algorithms([PR](https://github.com/QuantEcon/Games.jl/pull/115))
[Fictitious Play(Python)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/fictplay_py.ipynb)
[Fictitious Play(Julia)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/fictplay_jl.ipynb)
[Local Interaction(Python)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/localint_py.ipynb)
[Local Interaction(Julia)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/localint_jl.ipynb)
[Best Response Dynamics(Python)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/brd_py.ipynb)
[Best Response Dynamics(Julia)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/brd_jl.ipynb)
[Logit Response Dynamics(Python)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/logitdyn_py.ipynb)
[Logit Response Dynamics(Julia)](https://nbviewer.jupyter.org/github/QuantEcon/game-theory-notebooks/blob/learning_algos/logitdyn_jl.ipynb)

### CODE REVIEW

**Comment by Yuya-Furusawa** [comment]
@MKobayashi23m (cc: @oyamad)
Thanks for [your comment](https://github.com/QuantEcon/Games.jl/issues/127#issuecomment-606833987)!

I'm not sure if I should write about the detailed explanation of terminologies, such as potential game and IESDS.
As you pointed out, these are helpful for readers, but not so important from fictitious play perspective.
I think the easiest way is to link wiki page.

**Comment by MKobayashi23m** [comment]
Oh, it would be the most efficient way. Thank you for you suggestion! I agree to do so.

**Comment by MKobayashi23m** [comment]
Additional comment on Fictitious play (Julia)

### On the explanation of time series
“Similary, you can omit initial actions and they choosed randomly.”
- ‘choosed’ → ‘chosen’

### In the explanation of graph of simulation for two player game
“which is the maixed strategy Nash Equilibrium of this game”
- ‘maixed’ → ‘mixed’

### An expression “DecreasingGain” in code cells
- When you create FictitiousPlay or StochasticFictitiousPlay type instances as in the 3rd,11th, 15th and 18th code cells, I observed an expression ‘DecreasingGain’. I would like some explanation to interpret them.

### Stochastic Fictitious Play with “constant gain”
- I would like some explanation on what “constant gain” means.

### On the explanation of the Cournot game Simulation
“Payoff matrix is seemes to be”
-“is seemes “ → “seems”

**Comment by MKobayashi23m** [comment]
Comments on Local Interaction (Julia)

As in fictplay, it would be better to put links to explain some concepts like risk-domination, Pareto-domination, super modular games, etc.

## On the “Local Interaction Game” part,

- In the definition of Γ(x), you used a set X. Isn’t it χ, which you defined first as the set of players? Also, in the part that formally defines local interaction game that begins with “Given a network (X,P)”, you are using a symbol, X, not χ, again. Also, in the definition of action configuration, and latter parts.

- Below the matrix

image


it seems you have put some picture, but it is displayed as ‘？’ Box. (Sorry if it is due to my environment. Ignore this comment in that case.)

“An action configuration is a function”
- The action configuration is a kind of new concept to readers, I guess. So I would like more explanation.


## On “The `LocalInteraction` class” part

### On Adjacency Matrix part

“Note that the weight on player 1's action player 2 (…) is different”
- This seems a kind of strange to me, because at the beginning of the notebook, you let P(x,y) = P(y,x) for all x,y ∈ χ.

### `time_series`
- It might be easily inferred, but it would be better to clarify what the second argument of `time_series` is (maybe the duration of the time series?)

## Examples

“In the current version of GraphPlot, these is no way to…”
- “these” → “there”

### 2 action case
### circle

“Construct a `LocalInteraction` with patoff matrix, which is given by coordination_game and adj_matrix.”
- “patoff” → “payoff”

### 3-action case

“In the above matrix, for example, first, second and bottom row correspond to… “
- “row” → “rows”
- Maybe not only the rows but columns.

**Comment by MKobayashi23m** [comment]
Comments on Best Response Dynamics (Julia)

# Model

For each model, I would like brief mathematical descriptions as well as verbal ones. It is a bit hard to clearly image the model only from verbal explanations.

## Best response dynamics

“At each round, the set of players is choosed, “
- “choosed” → “chosen”

## KMR model

“…as stational equilibrium.”
- “stational”→ “stationary”

“Under some conditions, this dynamics gives p-dominant equilibrium as stational equilibirum.”
- “stational equilibirum” → “stationary equilibrium”
- Links to explanation of p-dominance would be helpful.


# `brd.jl` usage

## `play` method

“`play` method requires `init_action_dist`, which is the current action distribution where first element indicates the number of players who takes action 0.”
- In the code sample, `init_action_dist` seems to be a vector, not a distribution. I thought the word “distribution” often denoted a probability distribution. I would like some clarification on that.


“In addition, you can choose initial action distribution from which the dynamics proceeds.”

## `time_series` method
- The same comment for the expression “distribution”

“If not specified, it is randomly choosed.”
- “choosed” → ”chosen”


# Examples

“The number of agents is set to zero and…”
- Not “zero” but “10”, I guess, looking at the code sample.

## Best Response Dynamics

- I would like you to explain what the vertical and horizontal axis are in each graph.

## Kandori-Mailath-Rob model (KMR model)

### coordination game

“To compare the results from best reponse dynamics see before, (A,A) becomes stational equilibrium even if the number of player who initially takes action A is small.”

- “reponse” → ”response”
- “stational” → ”stationary”
- “see before” → “see the above” …?

**Comment by MKobayashi23m** [comment]
Comments on Logit Response Dynamics (Julia)

# Logit Response Dynamics

“, for example, fictitious play, (myopic) best response dynamics, Kamdori-Mailath-Rob, sampling best response models”
- “Kamdori-Mailath-Rob” → “Kandori-Mailath-Rob”

## Model

“u_i : payoff function Denote…
- “Denote…” should start in a new line.

# `logitdyn.jl` usage

“The game have to be NormalFormGame instance.”
- “have” → “has”

## `play` method

“`play` method return a new action profile in the model.”
- “return” → “returns”

## `time_series` method

“time_series method returns a time series of action distributions.”
- Again, “distribution” sounds a bit new to me… It might be the lack of my knowledge, so in that case, please ignore my comment.
- Importantly, on the note book, the sample code for the `time_series` method yields an error.  `init_actions = [1, 1]` may be problematic…?

# Example

“As you can see, (B,B) is a stable state of this dynamics, and this state maximizers of the potential ρ.”
- “state maximizers of” → “state maximizes”? Perhaps.

- Some comments on the graph for young’s game might be useful as it has a bit different graph from the first game.

**Comment by MKobayashi23m** [comment]
Comments on notebooks for Python

As the descriptions independent from the programing languages are probably the same, I did not review those parts thoroughly. Please apply the comment on the notebooks for Julia when it is possible.

# Fictitious Play

## `StochasticFictitiousPlay` class
### Simulation, Three action game

“But Williams(2018) shows that if the variance of shocks is small, namely
σ<0.0821 in the normal case and λ>6 in the logit case, this equilibrium is unstable.”
- This description does not appear on the notebook for Julia, so maybe you can add this.
- Using parameter “σ” or “λ” and the values here might not be so helpful. Readers might not know the model in Williams(2018).

**Comment by MKobayashi23m** [comment]
Sorry for being late and for the comments being tedious, perhaps. 

From now on I'm going to 
- review the rest of the Python Notebook, and
- review the code itself (checking its readability, consistency among the modules, etc.)

I'm going to finish my review in a couple of days.

**Comment by Yuya-Furusawa** [comment]
Thanks for your review! I have corrected almost all of the points you pointed out.

- This problem of the picture in localint note isn't the fault of your environment. The picture is loaded from local path. I forgot to upload the picture when I change the repository. Sorry.
- In brd notes, I use the word, action "distribution" because we use "distribution" in the code. I use "frequency" in the notes additionally. Should I use "frequency" in the codes instead of "distribution"? (change `init_action_dist` to `init_action_freq`, for example)

I'm going to
- add the mathematical descriptions of brd models
- add the comments on young's game in logitdyn note

**Comment by MKobayashi23m** [comment]
Thank you for your response! 

Sorry, it will take some more time to finish the review...

By the way, on python notebooks,
- I'd be happy if you check whether the points on which I made comments in Julia-notebooks are fixed in Python ones, too. (E.g. the use of not defined 'X' instead of 'χ')
- Some topics (e.g. "Tree versus Ladder" in Python notebooks) are not implemented in Julia notebooks. If possible, it might be better to write them also in Julia ones. (I've not yet reviewed the codes themselves, so if Julia version does not have the corresponding features, please ignore this comment).

**Comment by Yuya-Furusawa** [comment]
> I'd be happy if you check whether the points on which I made comments in Julia-notebooks are fixed in Python ones, too. (E.g. the use of not defined 'X' instead of 'χ')

I fixed the points in Python notebook, too.

> Some topics (e.g. "Tree versus Ladder" in Python notebooks) are not implemented in Julia notebooks. If possible, it might be better to write them also in Julia ones.

In localint notebooks, we  couldn't implement the graph animation with Julia(Do you know how to implement it?). Due to this limitation, Localint Julia note mainly focus on how to use `localint` struct, and the explanations are summarized in Python notes.
Are there any other topics I forgot to write in Julia note?

**Pull request merged**
